import { Bi } from "./lang";

/* ============================================================
   THE TEN SYSTEMS — section headers + essays
   ============================================================ */
export type Section = { num: string; id: string; title: Bi; sub: Bi; body: Bi };

export const SECTIONS: Section[] = [
  {
    num: "01", id: "layer",
    title: { en: "What Is Additive Manufacturing?", zh: "增材制造，是什么？" },
    sub: { en: "Layer by layer, an object emerges from information", zh: "层接一层，物体从信息中浮现" },
    body: {
      en: "Take a digital 3D model. Slice it into thin horizontal cross-sections — sometimes a hair's width thick, sometimes a few microns. Feed those slices to a machine that can deposit material exactly where each cross-section says to: melted plastic, photo-cured resin, sintered metal powder, extruded concrete, even living cells in hydrogel. The machine builds one slice on top of the next, and a physical object grows out of pure description. That is the entire trick. Where traditional manufacturing carves an object out of a block (lathing, milling, drilling) or stamps it out of a mould, additive manufacturing constructs it from nothing, atom by atom of intent. The implication is bigger than any single object. A factory that can read shape directly from a file is a factory that can make anything its files describe — and the file can be redesigned, mailed, optimized, generated by AI, or printed by a different machine on the other side of the planet. Manufacturing becomes a programmable function of information.",
      zh: "拿一个数字 3D 模型。把它切成薄薄的水平横截面——有时一根发丝那么厚，有时只有几微米。把这些切片送入一台机器，它能精确地按每一层所示沉积材料：熔融塑料、光固化树脂、烧结金属粉末、挤出的混凝土，乃至水凝胶中的活细胞。机器一层叠一层地建造，于是一个物理对象从纯粹的描述中生长出来。这就是它的全部把戏。传统制造从一整块材料中雕出对象（车、铣、钻）或从模具中冲压出来；增材制造则从无中构造它，一原子接一原子的意图。其含义比任何单一对象都要大。一座能直接从文件中读取形状的工厂，是一座能造出其文件所能描述之任何事物的工厂——而文件可以被重新设计、寄送、优化、由 AI 生成，或由地球另一端的另一台机器打印。制造，变成信息的一个可编程函数。",
    },
  },
  {
    num: "02", id: "history",
    title: { en: "The History of Manufacturing", zh: "制造的历史" },
    sub: { en: "Stone, metal, machine, line, robot, code", zh: "石、金属、机器、流水线、机器人、代码" },
    body: {
      en: "Manufacturing is older than writing. Stone tools mark the first technology, and every century since has been a quiet revolution in how matter is shaped. Knapping flint. Casting bronze. Forging iron. Hand-spinning wool. Then in the 18th century a discontinuity: steam, factories, interchangeable parts. The 19th century: assembly lines, scientific management. The 20th: CNC, robotics, lean production. Through it all the underlying pattern stayed the same — material was shaped by removing it (subtraction), pressing it (forming) or moulding it. Each era reduced the cost per unit by scaling the machinery and shrinking the role of human muscle. Additive manufacturing is a discontinuity of a different shape: it reduces the cost not of mass production but of variety. Suddenly the marginal cost of producing two different objects and the marginal cost of producing two identical ones converge. That equality, applied at scale, dissolves the economic logic that has organized industry for two centuries.",
      zh: "制造比文字古老。石器标记了最早的技术，自那以来的每一个世纪，都是关于「物质如何被塑形」的一场静默革命。打制燧石。铸造青铜。锻打铁器。手工纺羊毛。然后在 18 世纪出现了断点：蒸汽、工厂、可互换零件。19 世纪：流水线、科学管理。20 世纪：数控、机器人、精益生产。贯穿一切的底层模式始终如一——材料通过被去除（减法）、被压制（成形）或被浇铸来塑形。每一个时代都通过放大机器、压缩人类肌肉的角色来降低单件成本。增材制造，是另一种形状的断点：它降低的不是大批量生产的成本，而是品种的成本。突然之间，生产两个不同对象的边际成本，与生产两个相同对象的边际成本，趋于一致。这一相等性，被推向规模，便会溶解组织工业两个世纪之久的经济逻辑。",
    },
  },
  {
    num: "03", id: "materials",
    title: { en: "Materials Science & Printable Matter", zh: "材料科学与可打印之物" },
    sub: { en: "What you can print is what you can civilize", zh: "你能打印什么，就能让什么文明化" },
    body: {
      en: "Every leap in human capability has tracked a material. Stone-age, bronze-age, iron-age, silicon-age. Additive manufacturing's reach is now constrained by the materials it can deposit reliably — and that frontier moves every quarter. Plastics (PLA, ABS, PETG) are mature. Photopolymer resins give micron precision. Sintered metals — titanium, stainless, Inconel, aluminium — print parts that fly in jet engines and orbit on satellites. Ceramics, concrete, glass, graphene composites, carbon-fiber-reinforced thermoplastics are all printable today. Functional materials follow: printable circuits, printed batteries, printed transparent optics, printed magnets. The far frontier is living matter — hydrogel scaffolds seeded with cells, vasculature, eventually whole organs. Each new printable material is not just a new product but a new civilizational verb: 'house', 'organ', 'satellite', 'lung'. The unit of progress isn't the printer; it is what the printer can hold in its print head.",
      zh: "人类能力的每一次跃迁，都跟随一种材料。石器时代、青铜时代、铁器时代、硅器时代。增材制造的触及范围，如今受限于它能可靠沉积的材料——而那道前沿，每一个季度都在移动。塑料（PLA、ABS、PETG）已成熟。光敏树脂提供微米级精度。烧结金属——钛、不锈钢、Inconel、铝——能打印在喷气发动机中飞行、在卫星上环绕的零件。陶瓷、混凝土、玻璃、石墨烯复合材料、碳纤维增强热塑性塑料，今日皆可打印。功能材料随之而来：可打印电路、被打印的电池、被打印的透明光学元件、被打印的磁铁。最远的前沿是活物——播种了细胞的水凝胶支架、血管系统，最终是整器官。每一种新的可打印材料，不只是一个新产品，而是一个新的文明动词：「居住」、「器官」、「卫星」、「肺」。进步的单位，不是打印机；而是打印机的喷头里能装下什么。",
    },
  },
  {
    num: "04", id: "ai",
    title: { en: "AI-Generated Design & Generative Engineering", zh: "AI 生成设计与生成式工程" },
    sub: { en: "Machines now design objects no human would imagine", zh: "机器如今设计着人类不会去想象的对象" },
    body: {
      en: "Give a generative-design system a set of constraints — load this bracket must bear, weight it must not exceed, materials it can use — and it returns geometry humans would never draw. Twisting filigreed shells; branching internal lattices; organic forms that look grown rather than built. Topology optimization has been around for decades, but coupling it with additive manufacturing transformed it from an academic exercise into a production tool: the printer can fabricate the shapes the algorithm finds, so the algorithm is free to find shapes no mould could ever release. Aircraft brackets weigh 40% less. Heat exchangers route fluid through paths a human engineer would not have proposed because they would have been unbuildable. Increasingly the algorithm is not just an optimiser but a generator — a diffusion-style model that proposes whole classes of design candidates from text or scattered constraints. The question shifts from 'how do I design this part' to 'what specification do I want the search to satisfy'.",
      zh: "给一个生成式设计系统一组约束——这个支架必须承受的载荷、不能超过的重量、可用的材料——它返回的是人类绝不会画出的几何。扭转的镂空壳体；分支的内部点阵；看起来像是生长出来而非被建造出来的有机形态。拓扑优化已存在数十年，但把它与增材制造耦合起来，便将其从学院练习变成了生产工具：打印机能制造算法找到的形状，所以算法得以自由地去找模具永远无法脱模的形状。飞机支架轻 40%。换热器以人类工程师不会提出的路径输导流体——因为那些路径本不可建造。算法越来越不只是一个优化器，而是一个生成器——一个扩散式模型，从文本或散落的约束中提出整类设计候选。问题从「我该如何设计这个零件」转为「我希望搜索去满足的规约是什么」。",
    },
  },
  {
    num: "05", id: "distributed",
    title: { en: "Distributed Manufacturing & Decentralized Industry", zh: "分布式制造与去中心化工业" },
    sub: { en: "When the factory fits on a desk, the supply chain dissolves", zh: "当工厂塞进一张桌子，供应链便消解了" },
    body: {
      en: "A digital file can be at every printer on Earth in a second. If most of what a factory does can be reproduced by a smaller, cheaper, more flexible machine sitting in a workshop in São Paulo or a community fab-lab in Nairobi, then the economics of centralized manufacturing change. Industrial concentration in the 20th century was, in part, the consequence of high fixed costs of capital equipment; the bigger the factory, the lower the unit cost. If a printer the size of a refrigerator can produce a custom hearing aid, a replacement gear, a prosthetic limb, then the cheapest path to a part might be a local network of printers rather than a global container ship. Reality is in between. For mass-produced commodity goods, traditional manufacturing still wins on cost. For low-volume, high-customization, geographically dispersed, urgently-needed parts — the long tail — distributed printing is already winning. The end state is a hybrid: a planet covered in cheap general-purpose fabricators, fed by a small number of specialized centralized factories, with bits flowing freely and atoms flowing only when bits cannot.",
      zh: "一份数字文件，可以一秒之内抵达地球上的每一台打印机。如果一座工厂所做的大部分事情，都能被一台坐落在圣保罗的小作坊或内罗毕的社区 fab-lab 里、更小、更便宜、更灵活的机器复现，那么集中化制造的经济学便会改变。20 世纪的工业集中，部分上是资本设备高固定成本的结果；工厂越大，单件成本越低。若一台冰箱大小的打印机能制造一个定制助听器、一个替换齿轮、一具假肢，那么抵达一个零件的最便宜路径，或许是一张本地的打印机网络，而非一艘环球的集装箱船。现实介于两者之间。对于大规模生产的商品，传统制造在成本上仍胜出。对于低批量、高定制、地理分散、紧急所需的零件——长尾——分布式打印已在胜出。终态是一种混合：一颗被廉价、通用的制造机所覆盖的行星，由少数高度专业化的集中工厂喂给，比特自由流动，只有比特无法做到时，原子才流动。",
    },
  },
  {
    num: "06", id: "bio",
    title: { en: "Bioprinting, Organs & Synthetic Life", zh: "生物打印、器官与合成生命" },
    sub: { en: "What if biology itself becomes a print target?", zh: "若生物学本身成为一种打印目标？" },
    body: {
      en: "The same logic — slice digital model, deposit material layer by layer — applied to living matter. The 'ink' is now a hydrogel laden with living cells: skin cells, muscle cells, stem cells, vascular cells. Print a flat sheet and you have a graft. Print a complex tissue with channels and you can perfuse it with nutrients. Print a vascularized organ and, in principle, you can transplant it. The science is real but young. Functional printed skin patches are now used clinically for burns. Cartilage scaffolds, corneas, sections of bladder and trachea have all been printed and implanted in research settings. A whole printed kidney remains years away — the vascular density required is enormous and the cells must keep behaving after print. Beyond medicine, bioprinting opens stranger doors: cultured meat, printed neural networks for research, printed organoids that mimic disease. The hardest questions are not technical but human. Whose organs print first? Who owns the cell lines? When is a printed organ the same person's organ?",
      zh: "同样的逻辑——切分数字模型，逐层沉积材料——应用于活物。「墨水」如今是装满活细胞的水凝胶：皮肤细胞、肌肉细胞、干细胞、血管细胞。打印一张平片，便得一块移植物。打印一种带通道的复杂组织，便能用养分灌注它。打印一个被血管化的器官，原则上，便能移植它。科学是真实的，但年轻。功能性的打印皮肤贴片，如今已在烧伤临床上使用。软骨支架、角膜、膀胱与气管的部分，皆已在研究环境中被打印并被植入。完整打印的肾脏仍数年之外——所需的血管密度极其巨大，且细胞在打印后必须持续作出反应。在医学之外，生物打印打开了更陌生的门：培养肉、用于研究的打印神经网络、模拟疾病的打印类器官。最艰难的问题不是技术性的，而是人性的。谁的器官先被打印？谁拥有那些细胞系？一个被打印的器官，何时才算同一人的器官？",
    },
  },
  {
    num: "07", id: "mega",
    title: { en: "Megastructures, Housing & Printed Cities", zh: "宏构、住所与被打印的城市" },
    sub: { en: "When the printer is bigger than the building it makes", zh: "当打印机比它所造的建筑还大" },
    body: {
      en: "Scale up the print head. Hang it from a gantry the size of a building. Replace plastic with concrete or earth. Now the printer can extrude a wall in a single continuous bead, building a house in 24 hours for a fraction of conventional cost — and using shapes a bricklayer would never agree to. Companies like ICON, Apis Cor, Mighty Buildings, Cazza, WASP have printed homes in the US, Mexico, the Netherlands, Russia, Italy. Bridges have been printed in steel and stainless concrete. Curved load-bearing walls — historically a luxury — become routine because the printer doesn't care about cross-section symmetry. Construction-scale printing is not just cheaper housing. It is an architecture freed from the discipline of rectangular forms, which were largely a product of how stones and bricks and beams behave under hand. Whether printed cities are beautiful, durable, or socially better is still uncertain. Their unit economics already work in many cases. The deeper question is whether housing — long the largest investment a family makes and the largest physical artifact in a city — gets pulled into the post-additive economic regime, with all that implies for ownership, scarcity, and urban form.",
      zh: "把打印头放大。把它挂在一台建筑般大的龙门架上。把塑料换成混凝土或泥土。如今打印机能以一条连续的珠串挤出一面墙，用传统成本的一小部分在 24 小时内造出一座房子——并使用泥瓦匠绝不会同意的形状。ICON、Apis Cor、Mighty Buildings、Cazza、WASP 等公司，已在美国、墨西哥、荷兰、俄罗斯、意大利打印了住宅。桥梁已被以钢与不锈混凝土打印。曲面承重墙——历史上是奢侈——成为家常便饭，因为打印机不在意横截面的对称。建筑尺度的打印，不只是更便宜的住所。它是一种从矩形形态的纪律中解放出来的建筑——而那种纪律，在很大程度上是石头、砖块、梁木在人手之下行为的产物。被打印的城市是否美丽、耐久、在社会意义上是否更好，仍不确定。它们在许多情形下的单位经济学已成立。更深的问题是：住房——长期以来一个家庭最大的投资，也是城市中最大的物理工艺品——是否会被拉进后增材的经济范式，连带其对所有权、稀缺与城市形态的全部意味。",
    },
  },
  {
    num: "08", id: "nano",
    title: { en: "Nanotechnology & Programmable Matter", zh: "纳米技术与可编程物质" },
    sub: { en: "When matter becomes addressable at the atom", zh: "当物质在原子尺度上变得可寻址" },
    body: {
      en: "The far horizon. Drexler-style atomically precise manufacturing — molecular machines that place each atom exactly where the blueprint says — has been simultaneously dismissed as fantasy and stubbornly pursued by a fringe of serious researchers. Whatever its eventual feasibility, the conceptual destination is clear: matter becomes addressable at the level of its constituents. Programmable matter goes further: materials whose macroscale properties (stiffness, color, conductivity, shape) are reprogrammable from software in real time. Robotic 'claytronics' is one form; shape-memory alloys and liquid crystals are softer versions. DNA origami already lets biologists fold nucleic-acid strands into nanostructures with single-base precision. Each of these is an attempt to dissolve the line between hardware and software: matter that holds state, accepts updates, and answers to a protocol. None is yet a general-purpose technology. All are early signals of a regime in which the physical world becomes, increasingly, a substrate on which information runs.",
      zh: "最远的地平线。Drexler 式的原子级精确制造——把每一个原子精确放在蓝图所示位置的分子机器——曾被同时斥为幻想，并被一小撮严肃的研究者执拗地追求。无论其最终可行性如何，概念上的目的地是明确的：物质，在其组成层面变得可寻址。可编程物质走得更远：材料，其宏观属性（刚度、颜色、导电性、形状）可在实时中、由软件重新编程。机器人「claytronics」是一种形式；形状记忆合金与液晶是更柔软的版本。DNA 折纸已让生物学家以单碱基精度，把核酸链折叠成纳米结构。每一项，都是消解硬件与软件之边界的尝试：能持有状态、接受更新、应答某一协议的物质。其中没有一项已成为通用技术。所有这些，都是某一范式的早期信号——在那范式中，物理世界，越来越多地成为信息所运行其上的基底。",
    },
  },
  {
    num: "09", id: "space",
    title: { en: "Space Manufacturing & Post-Scarcity Civilization", zh: "太空制造与后稀缺文明" },
    sub: { en: "Mine asteroids, print factories, repeat", zh: "采矿小行星，打印工厂，循环往复" },
    body: {
      en: "The economics of getting matter into orbit are brutal: a kilogram to low-Earth orbit still costs thousands of dollars, and to the lunar surface or beyond, much more. Any structure that can be built in orbit out of in-orbit material — asteroid-mined metal, lunar regolith, recycled spacecraft — beats anything shipped up from Earth. Additive manufacturing in vacuum is harder (no convection cooling, no easy build-plate adhesion) but solvable, and several companies are already printing on the ISS. The longer arc: self-replicating fabricators that can land on a planetary body, mine its surface, refine raw material and use it to print more fabricators. Once a civilization has this loop in any form, the supply chain stops being a constraint. A Type-I civilization with self-replicating space fabricators is, by any earth-bound standard, post-scarcity for physical goods. The questions become political, ecological and existential rather than economic: not how much, but what should be made, by whom, and where.",
      zh: "把物质送入轨道的经济学是残酷的：一公斤送入近地轨道，至今仍要花费数千美元，送达月球表面或更远，则要多得多。任何能在轨道上、用轨道上的材料——小行星采的金属、月壤、回收的飞船——建造的结构，都胜过从地球运上去的任何东西。真空中的增材制造更难（没有对流冷却、没有简单的成形板粘附），但可解，且数家公司已在国际空间站上打印。更长的弧线：能着陆于行星体、采其地表、精炼原料、并以此打印更多制造机的自我复制制造机。一个文明一旦以任何形式拥有这一闭环，供应链便不再是约束。一个拥有自我复制太空制造机的 I 型文明，按任何地球本位的标准，对物理商品而言都是后稀缺。问题变成政治的、生态的与存在的，而非经济的：不是「多少」，而是「该造什么、由谁造、在哪造」。",
    },
  },
  {
    num: "10", id: "unified",
    title: { en: "The Unified Fabrication Model", zh: "统一制造模型" },
    sub: { en: "Programmable civilization = info × matter × intent", zh: "可编程文明 = 信息 × 物质 × 意图" },
    body: {
      en: "Set aside the slogan 'post-scarcity'. The honest synthesis emerging across additive manufacturing, materials science, AI design, distributed industry, bioprinting, construction-scale fabrication, nanotechnology and space manufacturing looks less like one technology and more like a shape. A 'programmable civilization' is one in which any object's blueprint can be transmitted as information, fabricated locally from whatever raw matter is available, optimized by AI for the constraints of its site, and recycled or revised when it's no longer needed. None of the pieces is complete. None of it is established as inevitable. But the trajectory is unmistakable: information becomes the master variable, matter becomes the substrate it runs on, and the role of centralized industry shifts from 'producer' to 'designer of the substrate' — and even that designer becomes increasingly algorithmic. The deepest question isn't whether the technology works. It is whether a civilization built around printable everything stays recognizable as a civilization at all.",
      zh: "暂且把「后稀缺」这一口号搁置一旁。在增材制造、材料科学、AI 设计、分布式工业、生物打印、建筑尺度的制造、纳米技术与太空制造之间正在浮现的、诚实的综合，看起来不太像一项技术，而更像一个形状。一个「可编程文明」是这样的：任何对象的蓝图都能作为信息被传输，从当地任何可用的原始物质中被本地制造，由 AI 针对其所在地的约束被优化，并在不再被需要时被回收或修订。其中没有一块完工。没有一块被立为必然。但轨迹无可错认：信息成为主变量，物质成为它所运行其上的基底，集中化工业的角色，从「生产者」转为「基底的设计者」——而连那位设计者，也越来越算法化。最深的问题不是技术是否奏效。而是一个被「万物可打印」围绕而建的文明，是否还能被辨认为一种文明。",
    },
  },
];

/* ============================================================
   CAPABILITY ERAS — manufacturing eras (CapabilityLadder)
   ============================================================ */
export type CapabilityEra = { key: string; era: Bi; name: Bi; externalizes: Bi; accent: string };
export const CAPABILITY_ERAS: CapabilityEra[] = [
  { key: "stone",      era: { en: "Stone (≈3.3 Myr BCE)",   zh: "石器（约前 330 万年）" }, name: { en: "Knapped stone tools",       zh: "打制石器" },        externalizes: { en: "The fist's grip — sharpness held outside the hand for the first time",                  zh: "拳头的抓握——尖锐第一次被外置于手之外" },                accent: "#777a9e" },
  { key: "bronze",     era: { en: "Bronze (≈3300 BCE)",      zh: "青铜（约前 3300 年）" },  name: { en: "Smelting and casting",      zh: "冶炼与铸造" },      externalizes: { en: "The mould — shape that holds itself even when the maker steps away",                   zh: "模具——即便造物者抽身离开，形状也能持守自身" },           accent: "#c98944" },
  { key: "iron",       era: { en: "Iron (≈1200 BCE)",        zh: "铁器（约前 1200 年）" },  name: { en: "Forging and tempering",     zh: "锻打与回火" },      externalizes: { en: "Local hardness — strength becomes specifiable, not just discovered",                   zh: "局部硬度——强度变得可被规约，不只是被发现" },             accent: "#9b6dff" },
  { key: "factory",    era: { en: "Industrial (1760)",        zh: "工业（1760）" },           name: { en: "Steam, factory, line",       zh: "蒸汽、工厂、流水线" }, externalizes: { en: "Muscle — power decoupled from the human body, then organized by Taylor and Ford",       zh: "肌肉——能量与人体脱钩，再由泰勒与福特组织起来" },         accent: "#3d8bfd" },
  { key: "cnc",        era: { en: "CNC (1952)",               zh: "数控（1952）" },           name: { en: "Numerically controlled cutting", zh: "数控切削" },     externalizes: { en: "The hand of the machinist — geometric precision now follows a program",                zh: "机床师傅的手——几何精度如今跟随一段程序" },               accent: "#f5a623" },
  { key: "robot",      era: { en: "Robotic (1961)",            zh: "机器人（1961）" },         name: { en: "Industrial robots",          zh: "工业机器人" },    externalizes: { en: "Repetition without fatigue — same gesture, again, perfectly, in any direction",         zh: "无疲惫的重复——同一动作，再来一次，完美，朝任何方向" }, accent: "#2fd4a8" },
  { key: "fdm",        era: { en: "Hobbyist 3D (1984 → 2005)",  zh: "桌面 3D（1984 → 2005）" }, name: { en: "Layer deposition",            zh: "层沉积" },         externalizes: { en: "Shape — for the first time, geometry has no mould, no tool, no fixture between idea and atom", zh: "形状——首次，几何在理念与原子之间没有模具、没有刀具、没有夹具" }, accent: "#6fb2ff" },
  { key: "metalprint", era: { en: "Metal AM (2000s)",          zh: "金属增材（2000s）" },       name: { en: "Sintered & melted metal",   zh: "烧结与熔融金属" }, externalizes: { en: "Industrial parts — engines, aerospace, surgical implants printed instead of cast",       zh: "工业零件——引擎、航空航天、外科植入物，被打印而非铸造" }, accent: "#ffd98c" },
  { key: "bioprint",   era: { en: "Bioprinting (2003 → today)", zh: "生物打印（2003 至今）" }, name: { en: "Living tissue deposition",   zh: "活组织沉积" },     externalizes: { en: "Repair — biology itself becomes a print target; tissues, vessels, eventually organs",   zh: "修复——生物学本身成为打印目标；组织、血管，最终是器官" }, accent: "#e87aaf" },
  { key: "construct",  era: { en: "Construction (2014 → today)",zh: "建筑（2014 至今）" },     name: { en: "Concrete-scale printing",    zh: "混凝土尺度打印" }, externalizes: { en: "Housing — homes and bridges grown layer by layer, freed from rectangular geometry",      zh: "住所——房屋与桥梁被一层层生长，从矩形几何中解放出来" }, accent: "#86e0c8" },
  { key: "nano",       era: { en: "Atomically precise (?)",     zh: "原子级精确（？）" },       name: { en: "Molecular assembly",         zh: "分子组装" },       externalizes: { en: "Atoms — matter becomes addressable at the level of its constituents",                   zh: "原子——物质在其组成层面变得可寻址" },                       accent: "#cab8ff" },
];

/* ============================================================
   EXTERNALIZATIONS — what each fabrication mode externalizes
   ============================================================ */
export type Externalization = { faculty: Bi; product: Bi; gloss: Bi; accent: string };
export const EXTERNALIZATIONS: Externalization[] = [
  { faculty: { en: "Muscle",         zh: "肌肉" },     product: { en: "Steam factory",      zh: "蒸汽工厂" },    gloss: { en: "Work decoupled from the body",                       zh: "工作与身体脱钩" },               accent: "#3d8bfd" },
  { faculty: { en: "Hand",           zh: "手" },        product: { en: "CNC machine",        zh: "数控机床" },     gloss: { en: "Precision decoupled from the craftsman",              zh: "精度与匠人脱钩" },                accent: "#f5a623" },
  { faculty: { en: "Mould",          zh: "模具" },     product: { en: "3D printer",         zh: "3D 打印机" },    gloss: { en: "Shape decoupled from tooling",                        zh: "形状与刀具脱钩" },                accent: "#6fb2ff" },
  { faculty: { en: "Designer",       zh: "设计师" },   product: { en: "Generative AI",      zh: "生成式 AI" },   gloss: { en: "Geometry decoupled from imagination",                 zh: "几何与想象脱钩" },                accent: "#2fd4a8" },
  { faculty: { en: "Factory",        zh: "工厂" },     product: { en: "Fab hub network",    zh: "制造枢纽网络" }, gloss: { en: "Production decoupled from geography",                 zh: "生产与地理脱钩" },                accent: "#9b6dff" },
  { faculty: { en: "Body",           zh: "身体" },     product: { en: "Bioprinter",         zh: "生物打印机" },   gloss: { en: "Repair decoupled from natural healing",               zh: "修复与自然愈合脱钩" },            accent: "#e87aaf" },
];

/* ============================================================
   MATERIALS / NEED-VALUE MAP — material × application matrix
   ============================================================ */
export type NeedTier = { key: string; level: Bi; need: Bi; lack: Bi; products: Bi; accent: string };
export const NEED_TIERS: NeedTier[] = [
  { key: "polymer",  level: { en: "Polymer",                   zh: "聚合物" },    need: { en: "Cheap, fast, complex shape", zh: "便宜、快、复杂形状" }, lack: { en: "Without printable plastic: no rapid prototypes, no custom enclosures, no replacement gears", zh: "没有可打印塑料：没有快速原型、没有定制外壳、没有替换齿轮" }, products: { en: "FDM brackets · SLA jewelry · SLS nylon parts · medical prototypes · everyday tooling",        zh: "FDM 支架 · SLA 首饰 · SLS 尼龙件 · 医疗原型 · 日常工装" },                  accent: "#3d8bfd" },
  { key: "metal",    level: { en: "Metal",                     zh: "金属" },       need: { en: "Strength, heat resistance, certification", zh: "强度、耐热、认证" }, lack: { en: "Without metal AM: no flightworthy parts, no custom turbines, no porous implants",            zh: "没有金属增材：没有适航零件、没有定制涡轮、没有多孔植入物" }, products: { en: "Titanium implants · jet-engine brackets · rocket combustion chambers · tooling inserts",      zh: "钛植入物 · 喷气引擎支架 · 火箭燃烧室 · 模具镶件" },                          accent: "#f5a623" },
  { key: "ceramic",  level: { en: "Ceramic & glass",           zh: "陶瓷与玻璃" }, need: { en: "Hardness, thermal stability, optical",  zh: "硬度、热稳定、光学" }, lack: { en: "Without ceramic AM: no custom dental crowns, no high-T sensors, no microfluidic chips",       zh: "没有陶瓷增材：没有定制牙冠、没有高温传感器、没有微流控芯片" }, products: { en: "Dental restorations · turbine vanes · μ-fluidic chips · printed lenses",                       zh: "牙科修复体 · 涡轮叶片 · 微流控芯片 · 打印透镜" },                            accent: "#cab8ff" },
  { key: "concrete", level: { en: "Concrete & earth",          zh: "混凝土与土" }, need: { en: "Cheap, structural, locally sourced",     zh: "便宜、结构性、本地材料" }, lack: { en: "Without construction AM: no rapid post-disaster housing, no doubly-curved walls",          zh: "没有建筑增材：没有灾后快速住所、没有双曲墙" }, products: { en: "Printed houses · pedestrian bridges · printed reefs · seawalls",                              zh: "打印房屋 · 步行桥 · 打印珊瑚礁 · 海堤" },                                      accent: "#86e0c8" },
  { key: "composite",level: { en: "Composite & graphene",      zh: "复合材料与石墨烯" }, need: { en: "Stiff, light, multifunctional",         zh: "刚、轻、多功能" }, lack: { en: "Without composite AM: no continuous-fiber wings, no integrated structural electronics",       zh: "没有复合材料增材：没有连续纤维机翼、没有一体化结构电子" }, products: { en: "CFRP drone frames · printed antennas · structural batteries",                                 zh: "CFRP 无人机框架 · 打印天线 · 结构电池" },                                      accent: "#ffd98c" },
  { key: "bio",      level: { en: "Bio (living cells)",         zh: "生物（活细胞）" }, need: { en: "Heal, integrate, regenerate",            zh: "愈合、整合、再生" }, lack: { en: "Without bioprinting: no off-the-shelf grafts, no vascularised organ research at scale",        zh: "没有生物打印：没有现货移植物、没有可规模化的血管化器官研究" }, products: { en: "Skin grafts · cartilage · organoids · vascular scaffolds · printed meat",                     zh: "皮肤移植物 · 软骨 · 类器官 · 血管支架 · 打印肉" },                              accent: "#e87aaf" },
];

/* ============================================================
   VALUE TERMS — what materials provide
   ============================================================ */
export type ValueTerm = { sym: string; name: Bi; gloss: Bi; sign: "+" | "−"; accent: string };
export const VALUE_TERMS: ValueTerm[] = [
  { sym: "Sₛ", name: { en: "Specific strength",     zh: "比强度" },    gloss: { en: "Load capacity per unit mass — the aerospace lever",      zh: "单位质量的承载——航空航天的杠杆" },     sign: "+", accent: "#3d8bfd" },
  { sym: "T",   name: { en: "Thermal range",         zh: "热稳定范围" }, gloss: { en: "Operating temperature — sets which sectors apply",       zh: "工作温度——决定哪些部门适用" },           sign: "+", accent: "#f5a623" },
  { sym: "ε",  name: { en: "Toughness",             zh: "韧性" },      gloss: { en: "Resistance to crack propagation — survival in field",     zh: "对裂纹扩展的抵抗——在现场存活" },        sign: "+", accent: "#2fd4a8" },
  { sym: "C",   name: { en: "Cost per kg",           zh: "每公斤成本" }, gloss: { en: "The economic gate; printable doesn't mean affordable",   zh: "经济闸门；可打印不等于负担得起" },       sign: "−", accent: "#9b6dff" },
  { sym: "v",  name: { en: "Print speed",            zh: "打印速度" },   gloss: { en: "Build rate; the bottleneck after material cost",          zh: "成形速率；继材料成本之后的瓶颈" },        sign: "+", accent: "#6fb2ff" },
  { sym: "η",  name: { en: "Defect rate",            zh: "缺陷率" },     gloss: { en: "Porosity, voids, anisotropy — the quiet quality cost",   zh: "孔隙率、空洞、各向异性——静默的质量代价" }, sign: "−", accent: "#e87aaf" },
];

/* ============================================================
   DESIGN PRINCIPLES — generative design / DfAM
   ============================================================ */
export type DesignPrinciple = { key: string; name: Bi; bad: Bi; good: Bi; accent: string };
export const DESIGN_PRINCIPLES: DesignPrinciple[] = [
  { key: "topology", name: { en: "Topology optimization",       zh: "拓扑优化" },     bad: { en: "Block of material, hand-drawn for the mill",                       zh: "一整块材料，凭手绘为铣床所设计" },                            good: { en: "Branching organic skeleton with load-aligned lattices",                   zh: "分支的有机骨架，配以与载荷对齐的点阵" },                       accent: "#3d8bfd" },
  { key: "lattice",  name: { en: "Internal lattice",             zh: "内部点阵" },     bad: { en: "Solid bulk where load doesn't need it",                           zh: "在不需要承载之处填满实体" },                                   good: { en: "Honeycomb, gyroid, or stochastic foam tuned to local stress",             zh: "蜂窝、陀螺面或随机泡沫，按局部应力调校" },                       accent: "#2fd4a8" },
  { key: "consolid", name: { en: "Part consolidation",           zh: "零件合并" },     bad: { en: "Twenty parts bolted together with fasteners and tolerances",       zh: "二十个零件用紧固件与公差栓接" },                              good: { en: "One printed component that integrates every function",                     zh: "一个打印件，整合每一项功能" },                                  accent: "#f5a623" },
  { key: "support",  name: { en: "Self-supporting geometry",     zh: "自支撑几何" },   bad: { en: "Overhangs needing scaffold that ruins surface and adds waste",     zh: "需要支撑的悬伸，损毁表面、增加废料" },                        good: { en: "Geometry that respects the 45° rule and prints clean",                     zh: "尊重 45° 规则、打印干净的几何" },                              accent: "#9b6dff" },
  { key: "channels", name: { en: "Internal channels",            zh: "内部通道" },     bad: { en: "Bolt cooling tubes onto the outside, lose surface area",            zh: "把冷却管栓在外面，损失表面积" },                              good: { en: "Conformal channels routed inside, exact to the heat field",                zh: "顺形通道在内部布管，与热场严丝合缝" },                          accent: "#6fb2ff" },
];

export type DesignDiscipline = { name: Bi; focus: Bi; accent: string };
export const DESIGN_DISCIPLINES: DesignDiscipline[] = [
  { name: { en: "CAD modeling",           zh: "CAD 建模" },     focus: { en: "Parametric solids; the design intent",         zh: "参数化实体；设计意图" },             accent: "#3d8bfd" },
  { name: { en: "Slicing",                zh: "切片" },          focus: { en: "G-code; the translator between geometry and machine", zh: "G-代码；几何与机器之间的翻译器" }, accent: "#6fb2ff" },
  { name: { en: "Topology optimization",  zh: "拓扑优化" },     focus: { en: "Math; remove every gram that does no work",     zh: "数学；移除每一克不做功之物" },         accent: "#2fd4a8" },
  { name: { en: "Generative AI",          zh: "生成式 AI" },    focus: { en: "Search; the algorithm proposes whole forms",    zh: "搜索；算法提出整体形态" },             accent: "#f5a623" },
  { name: { en: "Simulation",             zh: "仿真" },          focus: { en: "FEA + CFD; predict before you print",          zh: "FEA + CFD；打印前预测" },               accent: "#9b6dff" },
  { name: { en: "Material informatics",    zh: "材料信息学" },   focus: { en: "ML over alloy space; design the material too",  zh: "对合金空间的机器学习；连材料一起设计" }, accent: "#e87aaf" },
];

/* ============================================================
   PRODUCTION ERAS — distributed manufacturing
   ============================================================ */
export type ProductionEra = { key: string; name: Bi; era: Bi; cost: number; volume: number; gloss: Bi; accent: string };
export const PRODUCTION_ERAS: ProductionEra[] = [
  { key: "craft",   name: { en: "Craft",                 zh: "手工" },           era: { en: "< 1760",       zh: "1760 之前" }, cost: 0.95, volume: 0.05, gloss: { en: "One item, by hand, in a workshop",                          zh: "一件，手工，于作坊" },                          accent: "#777a9e" },
  { key: "factory", name: { en: "Factory",               zh: "工厂" },           era: { en: "1760 – 1913",  zh: "1760–1913" }, cost: 0.55, volume: 0.45, gloss: { en: "Steam, division of labor, interchangeable parts",          zh: "蒸汽、分工、可互换零件" },                        accent: "#3d8bfd" },
  { key: "line",    name: { en: "Mass production",       zh: "大规模生产" },     era: { en: "1913 – 1980",  zh: "1913–1980" }, cost: 0.10, volume: 0.95, gloss: { en: "Ford's assembly line, Toyota's lean — minimal cost per unit", zh: "福特流水线、丰田精益——最低单件成本" },           accent: "#f5a623" },
  { key: "cnc",     name: { en: "CNC + robots",          zh: "数控 + 机器人" },  era: { en: "1980 – 2010",  zh: "1980–2010" }, cost: 0.18, volume: 0.85, gloss: { en: "Numerically controlled cells, robotic arms, flexible lines", zh: "数控单元、机械臂、柔性产线" },                    accent: "#9b6dff" },
  { key: "additive",name: { en: "Additive + digital",    zh: "增材 + 数字" },    era: { en: "2010 – today", zh: "2010 至今" },  cost: 0.30, volume: 0.55, gloss: { en: "Same cost for one or many; geometry is free",                zh: "一件或多件成本相同；几何免费" },                  accent: "#6fb2ff" },
  { key: "distrib", name: { en: "Distributed fab hubs",  zh: "分布式制造枢纽" }, era: { en: "now → 2040",   zh: "当下 → 2040" }, cost: 0.40, volume: 0.50, gloss: { en: "Networks of small printers; bits flow, atoms stay local",     zh: "小型打印机的网络；比特流动，原子留在本地" },     accent: "#2fd4a8" },
  { key: "self",    name: { en: "Self-replicating",      zh: "自我复制" },       era: { en: "2050+ (?)",     zh: "2050+（？）" }, cost: 0.05, volume: 0.99, gloss: { en: "Speculative: fabricators that build more fabricators",        zh: "推测性：能造出更多制造机的制造机" },              accent: "#cab8ff" },
];

export type SupplyStage = { name: Bi; gloss: Bi; accent: string };
export const SUPPLY_STAGES: SupplyStage[] = [
  { name: { en: "Design (anywhere)",         zh: "设计（任意地点）" }, gloss: { en: "Engineer or AI; the file is the design",                  zh: "工程师或 AI；文件即设计" },                accent: "#3d8bfd" },
  { name: { en: "Transmit (a second)",        zh: "传输（一秒）" },     gloss: { en: "Internet to fab node",                                     zh: "互联网到制造节点" },                        accent: "#6fb2ff" },
  { name: { en: "Source feedstock (local)",   zh: "原料（本地）" },     gloss: { en: "Printer-grade material from a nearby supplier or recycler", zh: "来自就近供应商或回收者的打印级材料" },   accent: "#2fd4a8" },
  { name: { en: "Fabricate (hours)",          zh: "制造（数小时）" },   gloss: { en: "Layer-by-layer build at the destination",                 zh: "在目的地逐层成形" },                        accent: "#f5a623" },
  { name: { en: "Finish · inspect",           zh: "后处理 · 检验" },     gloss: { en: "Post-process, validate, certify",                          zh: "后处理、验证、认证" },                      accent: "#9b6dff" },
  { name: { en: "Use → recycle",              zh: "使用 → 回收" },       gloss: { en: "Service, then return feedstock to the loop",              zh: "使用之后，把原料归回循环" },                accent: "#e87aaf" },
];

/* ============================================================
   FABRICATION STACK — info → matter pipeline (SoftwareStack)
   ============================================================ */
export type SoftLayer = { key: string; name: Bi; examples: Bi; gloss: Bi; accent: string };
export const SOFT_LAYERS: SoftLayer[] = [
  { key: "intent",    name: { en: "Intent",                     zh: "意图" },             examples: { en: "Engineer, AI, end-user need",                                     zh: "工程师、AI、终端用户需求" },                gloss: { en: "What the part must do; the requirement",                     zh: "零件必须做什么；需求" },                       accent: "#cab8ff" },
  { key: "design",    name: { en: "Design",                     zh: "设计" },             examples: { en: "CAD (Fusion, SolidWorks); generative (nTopology, Spaceclaim AI)", zh: "CAD（Fusion、SolidWorks）；生成式（nTopology）" }, gloss: { en: "Geometry, parameters, constraints, materials",              zh: "几何、参数、约束、材料" },                    accent: "#3d8bfd" },
  { key: "simulate",  name: { en: "Simulate",                   zh: "仿真" },             examples: { en: "FEA (Ansys); CFD; print simulation",                              zh: "FEA（Ansys）；CFD；打印仿真" },             gloss: { en: "Predict; iterate before atoms are committed",                 zh: "预测；在原子被投入之前迭代" },                accent: "#6fb2ff" },
  { key: "slice",     name: { en: "Slice",                      zh: "切片" },             examples: { en: "Cura, PrusaSlicer, Magics; print path planning",                  zh: "Cura、PrusaSlicer、Magics；打印路径规划" }, gloss: { en: "Geometry → layers → motion commands (G-code)",               zh: "几何 → 层 → 运动指令（G-代码）" },            accent: "#2fd4a8" },
  { key: "control",   name: { en: "Motion control",             zh: "运动控制" },         examples: { en: "Stepper drivers; closed-loop servos; firmware",                  zh: "步进驱动；闭环伺服；固件" },                gloss: { en: "Execute coordinates to micron precision",                     zh: "把坐标以微米级精度执行出来" },                accent: "#f5a623" },
  { key: "deposit",   name: { en: "Material deposition",        zh: "材料沉积" },         examples: { en: "FDM extruder; SLA laser; SLS sintering; bioprint nozzle",          zh: "FDM 挤出；SLA 激光；SLS 烧结；生物打印喷头" }, gloss: { en: "The print head — where information becomes matter",          zh: "打印头——信息成为物质之处" },                accent: "#9b6dff" },
  { key: "feedback",  name: { en: "Sensing & feedback",         zh: "传感与反馈" },       examples: { en: "Infrared imaging; height probing; in-line ML defect detection",   zh: "红外成像；高度探测；在线 ML 缺陷检测" },    gloss: { en: "Close the loop; correct mid-print",                           zh: "闭环；打印中修正" },                          accent: "#e87aaf" },
  { key: "postproc",  name: { en: "Post-process",               zh: "后处理" },           examples: { en: "Anneal, machine, polish, certify",                                 zh: "退火、加工、抛光、认证" },                    gloss: { en: "Bring the print from 'done' to 'finished'",                    zh: "把打印件从『完成』带到『成品』" },           accent: "#86e0c8" },
];

/* ============================================================
   FABRICATION LOOP — design → slice → print → finish → repeat (AttentionLoop)
   ============================================================ */
export type LoopStage = { key: string; name: Bi; gloss: Bi; accent: string };
export const LOOP_STAGES: LoopStage[] = [
  { key: "spec",      name: { en: "Specify",            zh: "规约" },           gloss: { en: "Constraint set; what must the part do, where, for how long",      zh: "约束集；零件必须做什么、在何处、持续多久" },             accent: "#cab8ff" },
  { key: "generate",  name: { en: "Generate",            zh: "生成" },           gloss: { en: "Design proposed by human, AI, or hybrid loop",                     zh: "由人、AI 或混合循环提出设计" },                            accent: "#3d8bfd" },
  { key: "simulate",  name: { en: "Simulate",            zh: "仿真" },           gloss: { en: "Check predictions against the spec; iterate cheaply",              zh: "把预测与规约比对；廉价迭代" },                              accent: "#2fd4a8" },
  { key: "fabricate", name: { en: "Fabricate",            zh: "制造" },           gloss: { en: "Print, deposit, build — commit atoms to the geometry",             zh: "打印、沉积、建造——把原子投入几何" },                       accent: "#f5a623" },
  { key: "measure",   name: { en: "Measure",             zh: "测量" },           gloss: { en: "Scan, test, certify against the original spec",                    zh: "扫描、测试、对照原规约认证" },                              accent: "#6fb2ff" },
  { key: "learn",     name: { en: "Learn",               zh: "学习" },           gloss: { en: "Feedback to the design system; the loop tightens",                 zh: "反馈给设计系统；循环收紧" },                                accent: "#e87aaf" },
];

export type PersuasivePattern = { name: Bi; effect: Bi; accent: string };
export const PERSUASIVE_PATTERNS: PersuasivePattern[] = [
  { name: { en: "Continuous-loop optimization", zh: "持续闭环优化" }, effect: { en: "Every print teaches the next print's design",                           zh: "每一次打印教育下一次打印的设计" },                      accent: "#3d8bfd" },
  { name: { en: "Digital-twin parity",           zh: "数字孪生对齐" }, effect: { en: "Physical print mirrors simulated print; divergence is the signal",      zh: "物理打印对齐仿真打印；偏差即信号" },                    accent: "#2fd4a8" },
  { name: { en: "Self-learning machines",        zh: "自学习机器" },    effect: { en: "Printers tune their own parameters based on observed defects",          zh: "打印机基于观察到的缺陷调校自身参数" },                  accent: "#f5a623" },
  { name: { en: "Cross-facility transfer",       zh: "跨设施迁移" },    effect: { en: "What one machine learns, every same-class machine inherits",            zh: "一台机器所学，每一台同级机器继承" },                    accent: "#9b6dff" },
];

/* ============================================================
   MANUFACTURING PARADIGMS RADAR (MarketSystems)
   ============================================================ */
export type EconAxis = { key: string; name: Bi };
export const ECON_AXES: EconAxis[] = [
  { key: "geom",    name: { en: "Geometric freedom",       zh: "几何自由度" } },
  { key: "speed",   name: { en: "Throughput",               zh: "产能" } },
  { key: "cost",    name: { en: "Unit cost",                zh: "单件成本" } },
  { key: "custom",  name: { en: "Customization",            zh: "定制度" } },
  { key: "scale",   name: { en: "Scalability",              zh: "可扩展性" } },
  { key: "decent",  name: { en: "Decentralization",         zh: "去中心化" } },
];

export type MarketModel = { key: string; name: Bi; era: Bi; gloss: Bi; scores: Record<string, number>; accent: string };
export const MARKET_MODELS: MarketModel[] = [
  { key: "craft",    name: { en: "Craft",            zh: "手工" },         era: { en: "Pre-industrial",   zh: "前工业" }, gloss: { en: "One artisan, one item",                                  zh: "一名匠人，一件物" },                          scores: { geom: 0.7, speed: 0.1, cost: 0.05, custom: 0.95, scale: 0.05, decent: 0.8 }, accent: "#777a9e" },
  { key: "factory",  name: { en: "Mass production",  zh: "大规模生产" },   era: { en: "1913 – 1980",     zh: "1913–1980" }, gloss: { en: "Identical units; minimal cost; geographic concentration", zh: "完全相同的单件；最低成本；地理集中" }, scores: { geom: 0.3, speed: 0.95, cost: 0.95, custom: 0.1, scale: 0.95, decent: 0.15 }, accent: "#f5a623" },
  { key: "cnc",      name: { en: "CNC + robotics",    zh: "数控 + 机器人" }, era: { en: "1980 – 2010",    zh: "1980–2010" }, gloss: { en: "Programmable cells; flexible but capital-heavy",          zh: "可编程单元；柔性但重资本" },              scores: { geom: 0.55, speed: 0.7, cost: 0.7, custom: 0.45, scale: 0.7, decent: 0.3 }, accent: "#9b6dff" },
  { key: "additive", name: { en: "Additive",          zh: "增材" },         era: { en: "2010 – today",     zh: "2010 至今" }, gloss: { en: "Same cost per unit for any geometry; small batches viable",  zh: "任何几何同样的单件成本；小批量可行" },     scores: { geom: 0.95, speed: 0.35, cost: 0.4, custom: 0.95, scale: 0.55, decent: 0.7 }, accent: "#3d8bfd" },
  { key: "distrib",  name: { en: "Distributed fab",   zh: "分布式制造" },   era: { en: "Emerging",         zh: "正涌现" },     gloss: { en: "Networks of printers; bits flow, atoms stay local",       zh: "打印机网络；比特流动，原子留在本地" },     scores: { geom: 0.9, speed: 0.45, cost: 0.5, custom: 0.95, scale: 0.75, decent: 0.95 }, accent: "#2fd4a8" },
  { key: "self",     name: { en: "Self-replicating",  zh: "自我复制" },      era: { en: "Speculative",     zh: "推测性" },     gloss: { en: "Fabricators that build more fabricators",                  zh: "造出更多制造机的制造机" },                  scores: { geom: 1.0, speed: 0.85, cost: 0.05, custom: 1.0, scale: 1.0, decent: 1.0 }, accent: "#cab8ff" },
];

/* ============================================================
   AI DESIGN AUTONOMY LEVELS (AIProductSim → AIDesignSim)
   ============================================================ */
export type AutonomyLevel = { key: string; level: string; name: Bi; gloss: Bi; example: Bi; accent: string };
export const AUTONOMY_LEVELS: AutonomyLevel[] = [
  { key: "L0", level: "L0", name: { en: "Hand-modeled",          zh: "手工建模" },     gloss: { en: "Human draws every feature in CAD",                                     zh: "人类在 CAD 中绘制每一个特征" },                       example: { en: "Fusion 360 part designed by a mechanical engineer",                  zh: "由机械工程师设计的 Fusion 360 零件" },               accent: "#3d8bfd" },
  { key: "L1", level: "L1", name: { en: "Parametric",            zh: "参数化" },        gloss: { en: "Designer writes formulas; software fills in the geometry",             zh: "设计师写公式；软件填几何" },                          example: { en: "Grasshopper definition; Onshape feature script",                     zh: "Grasshopper 定义；Onshape 特征脚本" },                accent: "#6fb2ff" },
  { key: "L2", level: "L2", name: { en: "Topology-optimized",    zh: "拓扑优化" },     gloss: { en: "Solver removes mass under stress constraints",                         zh: "求解器在应力约束下移除质量" },                      example: { en: "Altair Inspire bracket; Ansys Discovery part",                       zh: "Altair Inspire 支架；Ansys Discovery 零件" },         accent: "#2fd4a8" },
  { key: "L3", level: "L3", name: { en: "Generative",             zh: "生成式" },        gloss: { en: "Software proposes whole families; human selects",                       zh: "软件提出整族；人类筛选" },                            example: { en: "Autodesk Generative Design; nTopology",                              zh: "Autodesk 生成式设计；nTopology" },                    accent: "#f5a623" },
  { key: "L4", level: "L4", name: { en: "AI-generated",            zh: "AI 生成" },       gloss: { en: "Diffusion / LLM models propose geometry from a text spec",            zh: "扩散 / LLM 模型从文本规约提出几何" },              example: { en: "3DALLE-style; CAD-LLM; latent CAD models",                           zh: "3DALLE 式；CAD-LLM；潜空间 CAD 模型" },               accent: "#9b6dff" },
  { key: "L5", level: "L5", name: { en: "End-to-end autonomous",   zh: "端到端自主" },    gloss: { en: "Spec → design → simulate → print → measure → respec, all by AI",       zh: "规约 → 设计 → 仿真 → 打印 → 测量 → 重新规约，全由 AI" }, example: { en: "Closed-loop fabrication agent (speculative)",                       zh: "闭环制造代理（推测性）" },                            accent: "#e87aaf" },
];

/* ============================================================
   INFO → MATTER MERGE (MergeSim)
   ============================================================ */
export type MergeStage = { key: string; name: Bi; distance: Bi; gloss: Bi; accent: string };
export const MERGE_STAGES: MergeStage[] = [
  { key: "draw",    name: { en: "Drawn",                    zh: "被绘制" },     distance: { en: "Drawing → machinist → mill",                              zh: "图纸 → 机床师傅 → 铣床" },                     gloss: { en: "Information sits on paper; matter is shaped by human hand",    zh: "信息在纸上；物质由人手塑形" },                       accent: "#777a9e" },
  { key: "cad",     name: { en: "Modeled",                  zh: "被建模" },     distance: { en: "CAD → CNC G-code → machine",                              zh: "CAD → 数控 G-代码 → 机床" },                  gloss: { en: "Geometry digital; tooling still mechanical",                   zh: "几何数字化；刀具仍机械化" },                          accent: "#3d8bfd" },
  { key: "sliced",  name: { en: "Sliced",                   zh: "被切片" },     distance: { en: "CAD → slicer → printer",                                  zh: "CAD → 切片 → 打印机" },                       gloss: { en: "Mould eliminated; the file is the part",                       zh: "模具被消除；文件即零件" },                            accent: "#6fb2ff" },
  { key: "generated",name: { en: "Generated",               zh: "被生成" },     distance: { en: "Spec → AI → printer",                                     zh: "规约 → AI → 打印机" },                        gloss: { en: "Design too is information; intent becomes the input",          zh: "设计本身也是信息；意图成为输入" },                    accent: "#2fd4a8" },
  { key: "instant", name: { en: "Instant",                  zh: "即时" },        distance: { en: "Speak → print → object exists",                            zh: "言说 → 打印 → 对象存在" },                    gloss: { en: "The latency between thinking and having shrinks to seconds",    zh: "「想到」与「拥有」之间的时延缩至秒级" },              accent: "#f5a623" },
  { key: "ambient", name: { en: "Ambient",                  zh: "弥漫式" },     distance: { en: "Environment fabricates as needed",                         zh: "环境按需制造" },                                gloss: { en: "Programmable matter; the world itself is the printer",          zh: "可编程物质；世界本身就是打印机" },                    accent: "#9b6dff" },
];

/* ============================================================
   SPACE / FUTURE — speculative end-states (Future cards at hero)
   ============================================================ */
export type Future = { name: Bi; horizon: Bi; desc: Bi; accent: string };
export const FUTURES: Future[] = [
  { name: { en: "Lunar regolith printer",        zh: "月壤打印机" },       horizon: { en: "2030s",       zh: "2030 年代" },      desc: { en: "Sinter Moon soil into roads and habitats; almost no material from Earth",                zh: "把月壤烧结成道路与栖息地；几乎没有材料来自地球" },              accent: "#cab8ff" },
  { name: { en: "Orbital manufacturing",          zh: "轨道制造" },         horizon: { en: "2030s – 2040s", zh: "2030 – 2040 年代" }, desc: { en: "Zero-g unlocks materials (ultra-pure fiber, organs without gravity-induced sag)",         zh: "零重力解锁材料（超纯纤维、不因重力下垂的器官）" },                 accent: "#3d8bfd" },
  { name: { en: "Asteroid metal foundry",         zh: "小行星金属冶炼厂" }, horizon: { en: "2050+",        zh: "2050+" },           desc: { en: "Mine, refine and print structural metal off-world; never lift another bolt",             zh: "在地外采掘、精炼并打印结构金属；再也无需运另一颗螺栓" },           accent: "#f5a623" },
  { name: { en: "Self-replicating fab",            zh: "自我复制制造机" },   horizon: { en: "?",            zh: "？" },              desc: { en: "A fabricator that builds another of itself from local material — von Neumann's loop",    zh: "一台从本地材料中造出另一台自己的制造机——冯·诺依曼的闭环" },         accent: "#e87aaf" },
];

/* ============================================================
   PROGRAMMABLE-CIVILIZATION CAPACITIES (FabricationPowerModel)
   ============================================================ */
export type Capacity = { sym: string; name: Bi; gloss: Bi; craft: number; industrial: number; ai: number };
export const CAPACITIES: Capacity[] = [
  { sym: "D",  name: { en: "Digital design",        zh: "数字设计" },         gloss: { en: "Captured intent — geometry, materials, constraints",      zh: "被捕获的意图——几何、材料、约束" },     craft: 0.15, industrial: 0.55, ai: 0.95 },
  { sym: "M",  name: { en: "Material engineering",   zh: "材料工程" },          gloss: { en: "Range of printable substances",                            zh: "可打印物质的范围" },                       craft: 0.35, industrial: 0.70, ai: 0.95 },
  { sym: "A",  name: { en: "AI optimization",         zh: "AI 优化" },           gloss: { en: "Generative + topology + search; design beyond intuition",   zh: "生成 + 拓扑 + 搜索；超越直觉的设计" },     craft: 0.05, industrial: 0.30, ai: 0.95 },
  { sym: "F",  name: { en: "Distributed fab",         zh: "分布式制造" },         gloss: { en: "Geographic spread of fabricators",                          zh: "制造机的地理分布" },                       craft: 0.95, industrial: 0.20, ai: 0.80 },
  { sym: "R",  name: { en: "Robotics & automation",  zh: "机器人与自动化" },   gloss: { en: "Hands-off, lights-out, continuous production",              zh: "无人值守、关灯、连续生产" },               craft: 0.05, industrial: 0.85, ai: 0.95 },
  { sym: "E",  name: { en: "Energy availability",    zh: "能量可得性" },        gloss: { en: "Cheap reliable power; the precondition of everything",      zh: "便宜可靠的电力；一切的前提" },           craft: 0.20, industrial: 0.80, ai: 0.95 },
  { sym: "B",  name: { en: "Bio-integration",        zh: "生物整合" },          gloss: { en: "Print living tissue; close the bio-fab gap",               zh: "打印活组织；闭合生物-制造的缝隙" },     craft: 0.0,  industrial: 0.10, ai: 0.65 },
  { sym: "I",  name: { en: "Info-to-matter",          zh: "信息到物质" },         gloss: { en: "Latency from bit to atom — the master variable",            zh: "从比特到原子的时延——主变量" },          craft: 0.05, industrial: 0.30, ai: 0.95 },
];

/* ============================================================
   RECURSIVE FABRICATION ENGINE (ProductRecursionSim)
   ============================================================ */
export type RecursionLayer = { k: string; name: Bi; scale: Bi; move: Bi; color: string };
export const RECURSION_LAYERS: RecursionLayer[] = [
  { k: "raw",      name: { en: "Raw material",           zh: "原始材料" },          scale: { en: "Filament, powder, resin, paste, regolith",       zh: "丝材、粉末、树脂、糊料、月壤" },             move: { en: "Stock feeds into a printer; printer becomes node",             zh: "原料喂入打印机；打印机成为节点" },                color: "#cab8ff" },
  { k: "machine",  name: { en: "Single machine",         zh: "单机" },              scale: { en: "One desktop printer, kg-scale parts",            zh: "一台桌面打印机，公斤级零件" },              move: { en: "Print a part you needed; share the file",                       zh: "打印你所需的零件；分享文件" },                    color: "#3d8bfd" },
  { k: "lab",      name: { en: "Print farm",             zh: "打印农场" },          scale: { en: "Dozens of machines, hot-swappable jobs",         zh: "数十台机器，可热换的作业" },                move: { en: "Service-bureau scale; batch jobs through a queue",              zh: "服务局规模；通过队列批处理作业" },                color: "#6fb2ff" },
  { k: "hub",      name: { en: "Fab hub",                zh: "制造枢纽" },          scale: { en: "Multi-process city facility; metal + polymer + ceramic", zh: "多工艺城市设施；金属 + 聚合物 + 陶瓷" }, move: { en: "Local node in a planetary print network",                       zh: "行星级打印网络中的本地节点" },                    color: "#2fd4a8" },
  { k: "network",  name: { en: "Distributed network",    zh: "分布式网络" },         scale: { en: "Thousands of hubs, one global directory",         zh: "数千个枢纽，一份全球目录" },                move: { en: "Files route to the nearest qualified printer",                  zh: "文件路由至最近合格打印机" },                      color: "#f5a623" },
  { k: "civ",      name: { en: "Civilizational substrate", zh: "文明基底" },         scale: { en: "Print as a planetary utility — like power, water",   zh: "打印作为行星级公共事业——像电力、水" },     move: { en: "Default mode of how objects come into being",                    zh: "对象诞生方式的默认模式" },                        color: "#9b6dff" },
  { k: "biolife",  name: { en: "Bio-integrated",         zh: "生物整合" },           scale: { en: "Print tissues, organs, food; biology accepts files",  zh: "打印组织、器官、食物；生物学接受文件" }, move: { en: "Medicine and agriculture become information services",         zh: "医学与农业成为信息服务" },                          color: "#e87aaf" },
  { k: "nano",     name: { en: "Atomically precise",     zh: "原子级精确" },          scale: { en: "Molecular assembly; nanometer placement",            zh: "分子组装；纳米级放置" },                    move: { en: "Hardware becomes addressable; matter holds state",              zh: "硬件变得可寻址；物质持有状态" },                  color: "#cab8ff" },
  { k: "orbit",    name: { en: "Orbital + lunar",        zh: "轨道 + 月面" },        scale: { en: "Print structures off-world from off-world material", zh: "在地外用地外材料打印结构" },                  move: { en: "Decouple manufacturing from Earth's gravity well",              zh: "把制造与地球引力井脱钩" },                          color: "#3d8bfd" },
  { k: "interplan",name: { en: "Interplanetary",         zh: "行星际" },             scale: { en: "Asteroid mining + self-replicating fab",            zh: "小行星采矿 + 自我复制制造" },              move: { en: "Civilizational matter supply becomes effectively unbounded",    zh: "文明级物质供应实际上无界" },                        color: "#86e0c8" },
];

/* ============================================================
   AI LAYER — the Fabrication Analyst: six lenses on the deep questions
   ============================================================ */
export type BigQ = { q: Bi; lens: { en: string } };
export const BIG_QUESTIONS: BigQ[] = [
  { q: { en: "When every object can be printed, what does it mean to make one well?",                       zh: "当每一个对象都能被打印，「把一个东西做好」还意味着什么？" }, lens: { en: "Craft · quality · the meaning of effort in a printable world" } },
  { q: { en: "If the file is the part, who owns the file — and who is liable when it fails?",               zh: "若文件即零件，谁拥有那份文件——以及当它失败时，谁负责？" }, lens: { en: "IP · liability · the politics of designs" } },
  { q: { en: "What happens to factories — and to the cities and lives built around them — when they shrink?", zh: "当工厂缩小，工厂、以及围绕它建起的城市与人生，会发生什么？" }, lens: { en: "Industrial geography · labor · the cost of cheap variety" } },
  { q: { en: "When a printed organ heals a person, in what sense is the organ theirs?",                     zh: "当一个被打印的器官治愈一个人，那个器官在何种意义上是他的？" }, lens: { en: "Bioethics · ownership · the printable body" } },
  { q: { en: "Is a civilization with self-replicating fabricators still recognizable as a civilization?",   zh: "一个拥有自我复制制造机的文明，还能被辨认为一种文明吗？" }, lens: { en: "Civilization scale · post-scarcity · what survives plenty" } },
];

export type AnalystLens = { key: string; role: Bi; blurb: Bi; accent: string };
export const ANALYST_LENSES: AnalystLens[] = [
  { key: "engineer",      role: { en: "Manufacturing engineer",    zh: "制造工程师" },      blurb: { en: "process, tolerance, throughput, quality",      zh: "工艺、公差、产能、质量" },                  accent: "#3d8bfd" },
  { key: "materials",     role: { en: "Materials scientist",        zh: "材料科学家" },       blurb: { en: "alloy space, microstructure, anisotropy",      zh: "合金空间、微观结构、各向异性" },              accent: "#f5a623" },
  { key: "robotics",      role: { en: "Robotics theorist",          zh: "机器人理论家" },     blurb: { en: "motion, autonomy, the closed loop",            zh: "运动、自主、闭环" },                          accent: "#2fd4a8" },
  { key: "futurist",      role: { en: "Industrial futurist",        zh: "工业未来学者" },     blurb: { en: "scale, decentralization, supply chains",       zh: "规模、去中心化、供应链" },                     accent: "#9b6dff" },
  { key: "nano",          role: { en: "Nanotechnology analyst",     zh: "纳米技术分析者" },   blurb: { en: "atomically precise, programmable matter",      zh: "原子级精确、可编程物质" },                     accent: "#6fb2ff" },
  { key: "civilization",  role: { en: "Civilization-systems researcher", zh: "文明系统研究者" }, blurb: { en: "long arc, power, what survives plenty",         zh: "长程弧线、权力、何者在富足中幸存" },           accent: "#ffd98c" },
];

export type AnalystTopic = { key: string; q: Bi; views: { lens: string; text: Bi }[] };
export const ANALYST_TOPICS: AnalystTopic[] = [
  {
    key: "what-is-am",
    q: { en: "What is additive manufacturing, really?", zh: "增材制造，究竟是什么？" },
    views: [
      { lens: "engineer",     text: { en: "Operationally, it is a class of fabrication processes where material is added — extruded, deposited, sintered, polymerized — to build a part layer by layer, directly from a digital model. There are seven ISO/ASTM categories; FDM, SLA, SLS, DMLS, binder jetting, material jetting, and DED among them. Each has its tolerance window, surface finish, and material list. Inside a shop, AM is simply another machine class — flexible, slow per part, exquisite at complexity.", zh: "操作上，它是一类制造工艺：通过添加材料——挤出、沉积、烧结、聚合——直接从数字模型逐层建造一个零件。有七个 ISO/ASTM 类别；其中 FDM、SLA、SLS、DMLS、粘结剂喷射、材料喷射、DED。每一类都有其公差窗口、表面质量与材料清单。在车间内，增材只是另一类机器——柔性、单件慢、对复杂度极致出色。" } },
      { lens: "futurist",     text: { en: "Strategically, AM is the first manufacturing technology where the unit cost is geometry-independent. Producing two different objects costs the same as producing two identical ones. That breaks the economic logic — mass production, supply chains, factory geography — that organized industry from 1913 onward. AM is not a printer; it is a re-distribution of where production happens and who owns it.", zh: "战略上，增材是首项单位成本与几何无关的制造技术。生产两个不同对象的成本，与生产两个相同对象相同。这打破了自 1913 年以来组织工业的经济逻辑——大规模生产、供应链、工厂地理。增材不是一台打印机；它是「生产在何处发生、由谁拥有」的重新分布。" } },
      { lens: "civilization", text: { en: "At civilization scale, AM is one of a small set of technologies that decouples a physical capability from a centralized infrastructure: like printing did for text, the personal computer for computation, and the internet for distribution. Each unbundled an industry. AM unbundles manufacturing — and the political consequences of that are not yet in the textbooks.", zh: "在文明尺度上，增材是少数几项把物理能力与集中化基础设施脱钩的技术之一：正如印刷术之于文本，个人电脑之于计算，互联网之于分发。每一项都解绑了一个行业。增材解绑了制造——而其政治后果，尚未写进教科书。" } },
    ],
  },
  {
    key: "matters-from-info",
    q: { en: "What does it mean for matter to come from information?", zh: "「物质源自信息」是什么意思？" },
    views: [
      { lens: "engineer",     text: { en: "In practice, very little. The CAD file is a representation; the printer is a translator; the part still has mass, atoms and tolerances. What's changed is the path: human design → digital description → automated execution, with no mould or human-shaped jig in the loop. The information is the design; the matter is still matter.", zh: "实务上，几乎不多。CAD 文件是一种表征；打印机是翻译者；零件仍有质量、原子与公差。改变的是路径：人类设计 → 数字描述 → 自动化执行，回路中没有模具、也没有由人手塑形的工装。信息是设计；物质仍是物质。" } },
      { lens: "nano",         text: { en: "At the limit, it can mean more. If atoms can be placed exactly, with feedback at the atomic scale, then any pattern of atoms — any material, any structure — becomes a function from blueprint to substance. That horizon is still distant. But the present-day printer already operates by the same in-principle logic; the only difference is resolution.", zh: "在极限上，它可以意味着更多。若原子能被精确放置，并在原子尺度上获得反馈，那么任何原子图样——任何材料、任何结构——便成为从蓝图到实体的一个函数。那道地平线仍很遥远。但今日的打印机，已按同样的原则性逻辑运作；唯一的差别是分辨率。" } },
      { lens: "civilization", text: { en: "Politically, it means whoever controls the design tools controls the supply. Files can be censored, encrypted, withheld, or smuggled. The contests of the 21st century around media files (music, video, software) will recur for objects — except the stakes are housing, weapons, organs, and infrastructure rather than entertainment.", zh: "政治上，它意味着控制设计工具者，控制供应。文件可以被审查、加密、扣留或走私。21 世纪围绕媒体文件（音乐、视频、软件）的争夺将在「对象」上重演——只是赌注是住房、武器、器官、基础设施，而非娱乐。" } },
    ],
  },
  {
    key: "centralized-or-distributed",
    q: { en: "Will manufacturing become centralized or distributed?", zh: "制造会走向集中，还是分布？" },
    views: [
      { lens: "engineer",     text: { en: "Both, in different layers. Commodity production — chips, screws, fasteners, mass-market goods — will stay centralized because traditional manufacturing still wins on unit cost. Specialty, custom, urgent and low-volume production will move toward local fab hubs. The combined system is hybrid: a planet of small flexible printers fed by a small number of specialized centralized factories.", zh: "在不同层面，两者皆是。商品生产——芯片、螺丝、紧固件、大众市场商品——将保持集中，因为传统制造在单件成本上仍胜出。特种、定制、紧急与小批量生产，将转向本地制造枢纽。组合系统是混合的：一颗满是小型柔性打印机的行星，由少数高度专业化的集中工厂供给。" } },
      { lens: "futurist",     text: { en: "The long arc is distribution, slowly. The trajectory is the same as electronics — mainframes to PCs to mobile to ambient — except mediated by the cost of feedstock and energy. By 2050 we should expect every city to host enough fab capacity to make most non-commodity objects locally; by 2100 every home. The question is whether democratic governance keeps up.", zh: "长程弧线，缓慢地，是分布。轨迹与电子学相同——主机到 PC 到移动到弥漫——只是受原料与能源成本调节。到 2050 年，我们应当预期每一座城市都拥有足够的制造能力，本地制造大多数非商品对象；到 2100 年，每一个家。问题是民主治理能否跟上。" } },
      { lens: "civilization", text: { en: "Distribution is fragile. Each fab node is a target; each design file is a vulnerability. A civilization that depends on shippable bits for its housing, medicine and parts is also a civilization whose supply chain runs on whoever controls the file servers — or whoever can shut them down. Centralization moves to a different layer.", zh: "分布是脆弱的。每一个制造节点都是目标；每一份设计文件都是脆弱点。一个把住房、医药、零件依赖于可发送比特的文明，其供应链也运行在「谁控制文件服务器」之上——或「谁能关闭它们」之上。集中化转移到了另一个层面。" } },
    ],
  },
  {
    key: "printable-body",
    q: { en: "What's the line between a printed organ and a person?", zh: "被打印的器官与一个人之间的界线在哪？" },
    views: [
      { lens: "engineer",     text: { en: "Technically: a printed organ uses the recipient's cells, prints them onto a scaffold, perfuses them, integrates them with the recipient's vasculature, and the immune system accepts them as self. By any operational test — function, ownership, indistinguishability — that organ is part of the person. The line is biology's, not engineering's.", zh: "技术上：一个被打印的器官，使用受者的细胞，把它们打印到支架上，灌注它们，与受者的血管系统整合，免疫系统把它们当作自体接受。按任何操作性检验——功能、所有权、不可区分——那个器官是这个人的一部分。界线是生物学的，不是工程的。" } },
      { lens: "civilization", text: { en: "Politically: as long as someone owns the print files, the print materials, and the printer, that person retains a foothold inside the recipient's body. 'Printed body' is also 'product body' — and product means licensing, updates, subscription. The line between organ and product gets fuzzier the more the printing depends on a corporate stack.", zh: "政治上：只要有人拥有打印文件、打印材料与打印机，那个人便在受者体内保留一处立足点。「被打印的身体」也是「产品的身体」——而产品意味着许可、更新、订阅。器官与产品之间的界线，随着打印越来越依赖企业堆栈而变得模糊。" } },
    ],
  },
  {
    key: "post-scarcity",
    q: { en: "If we get self-replicating fabricators, what comes next?", zh: "若我们获得自我复制制造机，接下来是什么？" },
    views: [
      { lens: "futurist",     text: { en: "If a fabricator can mine local material and build another fabricator from it, the supply chain stops being a constraint. Material is everywhere; energy is the only remaining input. Provided energy is cheap, the cost of physical goods asymptotes toward zero. By any reasonable definition, that civilization is post-scarcity for goods. Time, attention, and authority remain scarce.", zh: "若一台制造机能采本地材料、并用之造出另一台制造机，供应链便不再是约束。材料无处不在；能量是唯一剩下的输入。只要能量便宜，物理商品的成本渐近于零。按任何合理的定义，那个文明对商品而言便是后稀缺。时间、注意力与权威仍稀缺。" } },
      { lens: "nano",         text: { en: "From an information point of view, post-scarcity is just the dissolution of the cost of duplication. Software is post-scarcity; bandwidth and storage made it so. Hardware joins that club when atoms are addressable and energy is cheap. The bottleneck migrates upward — to design, to coordination, to what is worth printing.", zh: "从信息观点看，后稀缺仅仅是「复制成本」的消解。软件是后稀缺的；带宽与存储使之如此。硬件加入那个俱乐部，是在原子可寻址、能源便宜之时。瓶颈向上迁移——到设计、到协调、到「什么值得打印」。" } },
      { lens: "civilization", text: { en: "Honestly: most post-scarcity scenarios collapse into political ones. The hard problems become 'who decides what to make', 'how is replication regulated', and 'what stops a swarm of self-replicators from going feral'. The technology is the easy half. The civilization that survives plenty is the one that learns to coordinate around it.", zh: "诚实地说：多数后稀缺情境，会塌缩为政治情境。难题变成「谁决定造什么」、「复制如何被管制」、「什么阻止自我复制者群体失控」。技术是简单的一半。在富足中存活的文明，是学会围绕它进行协调的文明。" } },
    ],
  },
];
